import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createApp } from '../server.mjs';

// Set PORLI_TEST_BASE (for example http://localhost:8788 from `npm run cf:dev`) to run
// the same suite against the Cloudflare Worker. Each test then uses an isolated database.
const remote = process.env.PORLI_TEST_BASE?.replace(/\/$/, '');

async function fixture(t) {
  let app=null,base=remote;
  if(!remote){
    app=createApp({dbPath:':memory:',demo:true});
    await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
    t.after(async()=>{await new Promise(resolve=>app.server.close(resolve));app.db.close();});
    base='http://127.0.0.1:'+app.server.address().port;
  }
  const database='test-'+randomUUID();
  function client() {let cookie='';return async(path,method='GET',body,headers={})=>{const res=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',Cookie:cookie,'X-Porli-Database':database,...headers},body:body===undefined?undefined:JSON.stringify(body)});if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];return{status:res.status,data:await res.json()};};}
  const customer=client(),other=client(),staff=client(),admin=client(),visitor=client();
  for(const[c,role]of[[customer,'customer'],[other,'other'],[staff,'staff'],[admin,'admin']])assert.equal((await c('/auth/demo','POST',{role})).status,200);
  return{db:app?.db??null,base,customer,other,staff,admin,visitor,client};
}
test('public catalogue keeps modes, availability and private drafts separate',async t=>{const{visitor,staff}=await fixture(t);const buy=await visitor('/properties?mode=buy');assert.equal(buy.data.properties.length,2);assert.ok(buy.data.properties.every(p=>p.id==='grand-blue-hotel'||p.id==='demo-property-01'));assert.ok(buy.data.properties.every(p=>p.mode==='buy'&&p.transaction_status==='available'));assert.equal((await visitor('/properties?mode=rent')).data.properties.length,2);assert.equal((await visitor('/properties?mode=buy&pending=1')).data.properties.length,3);assert.equal((await visitor('/properties/garden-cottage')).status,404);assert.equal((await visitor('/properties/balcony-apartment')).status,404);assert.equal((await staff('/properties/garden-cottage')).status,200);assert.equal((await visitor('/properties?mode=buy&location=nowhere')).data.total,0);assert.equal((await visitor('/properties?mode=buy&min=-10')).status,400);assert.equal((await visitor('/admin/properties')).status,401);});
test('saves are idempotent, persistent and scoped to current account',async t=>{const{customer,other,visitor}=await fixture(t);const body={property_id:'demo-property-01'};assert.equal((await visitor('/saves','POST',body)).status,401);await customer('/saves','POST',body);await customer('/saves','POST',body);assert.deepEqual((await customer('/saves')).data.ids,[body.property_id]);assert.deepEqual((await other('/saves')).data.ids,[]);await customer('/saves','DELETE',body);assert.deepEqual((await customer('/saves')).data.ids,[]);});
test('message retries reuse one thread and other accounts cannot read it',async t=>{const{customer,other,staff}=await fixture(t);const body={property_id:'demo-property-01',body:'Is there afternoon sun?',client_key:'retry-1'};const a=await customer('/conversations','POST',body),b=await customer('/conversations','POST',body);assert.equal(a.data.id,b.data.id);assert.equal((await customer('/conversations/'+a.data.id)).data.messages.length,1);assert.equal((await other('/conversations/'+a.data.id)).status,404);assert.equal((await other('/conversations/'+a.data.id+'/messages','POST',{body:'unauthorised',client_key:'hack'})).status,404);assert.equal((await staff('/conversations/'+a.data.id+'/messages','POST',{body:'Yes, it does.',client_key:'staff-1'})).status,200);assert.equal((await customer('/conversations/'+a.data.id)).data.messages.length,2);});
test('notes never reach customer responses and reading or noting is not replying',async t=>{const{customer,staff}=await fixture(t);const{id}= (await customer('/conversations','POST',{property_id:'demo-property-01',body:'Hello team',client_key:'m1'})).data;assert.equal((await staff('/admin/dashboard')).data.awaiting,1);await staff(`/conversations/${id}/read`,'POST',{});await staff(`/conversations/${id}/notes`,'POST',{body:'PRIVATE NOTE'});assert.equal((await staff('/admin/dashboard')).data.awaiting,1);const view=await customer('/conversations/'+id);assert.equal(view.data.notes,undefined);assert.ok(!JSON.stringify(view).includes('PRIVATE NOTE'));assert.equal((await customer(`/conversations/${id}/notes`,'POST',{body:'forged'})).status,403);await staff(`/conversations/${id}/messages`,'POST',{body:'A human reply',client_key:'reply1'});assert.equal((await staff('/admin/dashboard')).data.awaiting,0);});
test('metrics count people and property threads, never message volume',async t=>{const{customer,staff}=await fixture(t);for(let i=0;i<5;i++)await customer('/conversations','POST',{property_id:i<3?'demo-property-01':'demo-property-02',body:'Question '+i,client_key:'metric-'+i});const d=(await staff('/admin/dashboard')).data;assert.equal(d.people,1);assert.equal(d.enquired,2);assert.equal(d.new_conversations,2);});
test('inspection confirmation enforces capacity atomically and requests are not bookings',async t=>{const{customer,other,staff}=await fixture(t);const starts_at=new Date(Date.now()+5*86400000).toISOString();assert.equal((await staff('/admin/slots','POST',{property_id:'demo-property-01',starts_at,capacity:1})).status,201);const slot=(await customer('/properties/courtyard-house')).data.slots.find(s=>s.capacity===1);const payload={property_id:'demo-property-01',slot_id:slot.id};const a=(await customer('/inspections','POST',payload)).data.id,b=(await other('/inspections','POST',payload)).data.id;assert.equal((await customer('/inspections','POST',payload)).data.id,a);assert.equal((await customer('/inspections')).data.inspections[0].status,'requested');assert.equal((await customer('/inspections/'+a,'PATCH',{status:'confirmed'})).status,403);const results=await Promise.all([staff('/inspections/'+a,'PATCH',{status:'confirmed'}),staff('/inspections/'+b,'PATCH',{status:'confirmed'})]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal((await other('/inspections/'+a,'PATCH',{status:'cancelled'})).status,404);});
test('closed enquiry does not sell property and new customer messages reopen it',async t=>{const{customer,staff}=await fixture(t);const{id}=(await customer('/conversations','POST',{property_id:'demo-property-01',body:'Hello',client_key:'open-1'})).data;await staff('/conversations/'+id,'PATCH',{stage:'closed'});assert.equal((await customer('/properties/courtyard-house')).data.property.transaction_status,'available');await customer('/conversations/'+id+'/messages','POST',{body:'Another question',client_key:'open-2'});assert.equal((await staff('/conversations/'+id)).data.stage,'in_conversation');});
test('publication validation, revision conflicts and outcome reversals',async t=>{const{staff,visitor,db}=await fixture(t);let draft=(await staff('/properties/garden-cottage')).data.property;assert.equal((await staff('/admin/properties','PATCH',{...draft,publication_state:'published'})).status,400);let p=(await staff('/properties/courtyard-house')).data.property;assert.equal((await staff('/admin/properties','PATCH',{...p,transaction_status:'leased'})).status,400);assert.equal((await staff('/admin/properties','PATCH',{...p,title:'Updated courtyard'})).status,200);assert.equal((await staff('/admin/properties','PATCH',{...p,title:'Stale overwrite'})).status,409);p=(await staff('/properties/courtyard-house')).data.property;assert.equal((await staff('/admin/properties','PATCH',{...p,transaction_status:'sold'})).status,200);assert.equal((await staff('/admin/dashboard')).data.outcomes,1);assert.equal((await visitor('/properties?mode=buy')).data.total,1);p=(await staff('/properties/courtyard-house')).data.property;await staff('/admin/properties','PATCH',{...p,transaction_status:'available'});assert.equal((await staff('/admin/dashboard')).data.outcomes,0);if(db)assert.equal(db.prepare('SELECT COUNT(*) n FROM audit').get().n,3);});
test('terminal properties block new enquiries and inspections but retain conversations',async t=>{const{customer,other,staff}=await fixture(t);const{id}=(await customer('/conversations','POST',{property_id:'demo-property-02',body:'Hello',client_key:'terminal1'})).data;let p=(await staff('/properties/garden-apartment')).data.property;await staff('/admin/properties','PATCH',{...p,transaction_status:'leased'});assert.equal((await other('/conversations','POST',{property_id:p.id,body:'new',client_key:'terminal2'})).status,409);assert.equal((await other('/inspections','POST',{property_id:p.id,proposed:'tomorrow'})).status,409);assert.equal((await customer('/conversations/'+id)).status,200);});
test('deactivation removes privileges immediately, customers cannot grant roles',async t=>{const{staff,admin,customer}=await fixture(t);assert.equal((await customer('/profile','PATCH',{name:'Alex',role:'admin'})).data.user.role,'customer');assert.equal((await customer('/admin/team','PATCH',{id:'demo-other',role:'admin',active:true})).status,403);assert.equal((await admin('/admin/team','PATCH',{id:'demo-staff',role:'staff',active:false})).status,200);assert.equal((await staff('/admin/properties')).status,401);});
test('password registration, logout, origin checks and upload rejection',async t=>{const{client,visitor,staff}=await fixture(t);const person=client();assert.equal((await person('/auth/register','POST',{name:'Test Person',email:'test@example.test',password:'A fictional passphrase 123'})).status,201);assert.equal((await person('/session')).data.user.role,'customer');await person('/auth/logout','POST',{});assert.equal((await person('/session')).data.user,null);assert.equal((await person('/auth/login','POST',{email:'test@example.test',password:'wrong'})).status,401);assert.equal((await person('/auth/login','POST',{email:'test@example.test',password:'A fictional passphrase 123'})).status,200);assert.equal((await visitor('/auth/demo','POST',{role:'admin'},{Origin:'https://evil.example'})).status,403);assert.equal((await staff('/admin/upload','POST',{data:'data:image/svg+xml;base64,PHN2Zz4='})).status,400);assert.equal((await staff('/admin/upload','POST',{data:'data:image/png;base64,ZmFrZQ=='})).status,400);});
test('the Grand Blue Hotel headline listing is real, priced on application and sorts last',async t=>{const{visitor}=await fixture(t);const buy=await visitor('/properties?mode=buy');const hotel=buy.data.properties.find(p=>p.id==='grand-blue-hotel');assert.ok(hotel);assert.equal(hotel.is_demo,false);assert.equal(hotel.price_label,'Price to be confirmed');assert.equal(hotel.currency,'THB');const asc=(await visitor('/properties?mode=buy&sort=price-asc')).data.properties;assert.equal(asc.at(-1).id,'grand-blue-hotel');const desc=(await visitor('/properties?mode=buy&sort=price-desc')).data.properties;assert.equal(desc.at(-1).id,'grand-blue-hotel');assert.ok(!(await visitor('/properties?mode=buy&min=1')).data.properties.some(p=>p.id==='grand-blue-hotel'));});
test('publishing without a price requires a price label, and property type and currency are validated',async t=>{const{staff}=await fixture(t);const media=[{url:'/assets/courtyard.webp',alt:'A'},{url:'/assets/apartment.webp',alt:'B'},{url:'/assets/townhouse.webp',alt:'C'}];const base={title:'Test Listing',mode:'buy',property_type:'hotel',price_minor:0,bedrooms:0,bathrooms:0,parking:0,locality:'Nowhere',summary:'Summary',description:'Description text.',publication_state:'published',transaction_status:'available',media,features:[]};assert.equal((await staff('/admin/properties','POST',{...base,price_label:''})).status,400);const created=await staff('/admin/properties','POST',{...base,price_label:'Price to be confirmed'});assert.equal(created.status,200);assert.equal(created.data.property.price_label,'Price to be confirmed');assert.equal((await staff('/admin/properties','POST',{...base,price_label:'x',property_type:'castle'})).status,400);assert.equal((await staff('/admin/properties','POST',{...base,price_label:'x',currency:'EUR'})).status,400);});
test('the hotel listing page returns its details and highlights arrays',async t=>{const{visitor}=await fixture(t);const res=await visitor('/properties/grand-blue-hotel-thailand');assert.equal(res.status,200);assert.ok(Array.isArray(res.data.property.details)&&res.data.property.details.length>0);assert.ok(Array.isArray(res.data.property.highlights)&&res.data.property.highlights.length>0);assert.ok(res.data.property.details.every(d=>Array.isArray(d)&&d.length===2));});
